### ISSUE TITLE
Error initializing rosdep in JustinaSetup.sh

### ISSUE THREAD

**Issue by gerava** [RobotJustina/JUSTINA#6]
I run the script JustinaSetup.sh as:
`sudo ./JustinaSetup.sh`

And in the middle of the installation show this:

> Initializing rosdep ...
> Error initializing rosdep.
> Warning: running 'rosdep update' as root is not recommended.
>   You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
>   Setting up environment ...
>   ROS installation complete.

and in the end, the installation was complete. 
So, I ran the suggestion:
`sudo rosdep fix-permissions`
and after:
`rosdep update`

**Comment by kyordhel** [comment]
@geraba

I will correct the script to prevent such behavior.
Thanks for the remark.

**Comment by kyordhel** [comment]
Deprecated.
