### ISSUE TITLE
Update needed on JustinaSetup.sh

### ISSUE THREAD

**Issue by rag21** [RobotJustina/JUSTINA#7]
"80-justinaRules.rules" install procedure to be add on JustinaSetup.sh, with the respective steps discussed on the "instructions" file. Also a manual fix can be attempt by every user following the same instructions...
sudo cp 80-justinaRules.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && sudo service udev restart && sudo udevadm trigger

At this time, every Justina launch file has been modified in order to maintain the USB connection via symlink instead of the "automatic" by-path connection generated on Linux.

**Comment by mnegretev** [comment]
Mauricio, could you please add this instructions asap? We need it to avoid hardware malfunctions.

**Comment by kyordhel** [comment]
Ok. Will try. 

I'm still stuck with the kinect2 thing. It breaks the Ubuntu install in virtual machines. Plus, there are some old code not compiling (without it?).

Will prioritise this.

**Comment by kyordhel** [comment]
Solved, but can't check hardware here. Could you please check it fresh installs properly before closing?

**Comment by rag21** [comment]
Works on fresh installs, this issue can be closed.
Probably I need to see how to update the udev rules when the hardware it's updated, maybe another script like updateRules.sh. I wil add an Issue later with more info.
